# WARNING: Não versionar este arquivo com dados reais em produção.
# Use Sealed Secrets, External Secrets Operator ou HashiCorp Vault.
apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
  namespace: fiap-games
  labels:
    app: catalog-api
type: Opaque
stringData:
  # SQL Server connection string
  ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=CatalogAPI;User Id=sa;Password=PosTech@123;TrustServerCertificate=True"

  # MongoDB credentials
  MongoDb__Username: "admin"
  MongoDb__Password: "PosTech@123"
